-- Restore the hybrid-search indexes dropped by 20260609150458_add_recipe_version.
-- That migration was auto-generated by `prisma migrate dev` drift detection: both
-- indexes are raw SQL (gin_trgm_ops / hnsw are not representable in schema.prisma),
-- so Prisma saw them as drift and dropped them. Recreate exactly as authored in
-- 20260528120000_hybrid_search_indexes (hnsw params match 20260609120700's recreate).
-- IF NOT EXISTS keeps this idempotent for any DB where they were restored by hand.

CREATE INDEX IF NOT EXISTS chunks_content_trgm_idx ON "chunks" USING gin ("content" gin_trgm_ops);

CREATE INDEX IF NOT EXISTS chunks_embedding_hnsw_idx ON "chunks" USING hnsw ("embedding" vector_cosine_ops) WITH (m = 16, ef_construction = 64);
